### ISSUE TITLE
Missing some units commonly used in SMIRNOFF force fields

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-units#7]
```
>>> from openff.units import unit
>>> unit.Quantity("2000.0 * kilocalories_per_mole/angstrom**2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/quantity.py", line 211, in __new__
    inst = ureg.parse_expression(value)
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/registry.py", line 1263, in parse_expression
    return build_eval_tree(gen).evaluate(
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/pint_eval.py", line 92, in evaluate
    left = self.left.evaluate(define_op, bin_op, un_op)
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/pint_eval.py", line 93, in evaluate
    return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/pint_eval.py", line 102, in evaluate
    return define_op(self.left)
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/registry.py", line 1264, in <lambda>
    lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/registry.py", line 1159, in _eval_token
    {self.get_name(token_text, case_sensitive=case_sensitive): 1}
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/pint/registry.py", line 643, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'kilocalories_per_mole' is not defined in the unit registry
>>> from openmm import unit
>>> unit.Quantity("2000.0 * kilocalories_per_mole/angstrom**2")
Quantity(value='2000.0 * kilocalories_per_mole/angstrom**2', unit=dimensionless)
```

**Comment by mattwthompson** [comment]
These are all I seem to have encountered experimenting with SMIRNOFF file parsing. Please feel free to open a new issue if there are other conveniences currently offered by OpenMM or other units packages that are not found here.
