### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by peastman** [openforcefield/openff-units#88]
I'm trying to install this package with

```
pip install -e .
```

It fails with the follow error.

```
    ERROR: Command errored out with exit status 1:
     command: /home/peastman/miniconda3/envs/cf/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/peastman/workspace/openff-units/setup.py'"'"'; __file__='"'"'/home/peastman/workspace/openff-units/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6goa737m
         cwd: /home/peastman/workspace/openff-units/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/peastman/workspace/openff-units/setup.py", line 10, in <module>
        import versioneer
      File "/home/peastman/workspace/openff-units/versioneer.py", line 332, in <module>
        class VersioneerConfig:
      File "/home/peastman/workspace/openff-units/versioneer.py", line 339, in VersioneerConfig
        versionfile_build: str | None
    TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by j-wags** [comment]
Which version of python are you on? I think this format of type annotation only works for python >=3.10

**Comment by peastman** [comment]
It's 3.9.  Is that no longer supported?

**Comment by j-wags** [comment]
Right, [in a part of our docs that we should make easier to find](https://docs.openforcefield.org/projects/toolkit/en/stable/users/developing.html#supported-python-versions), we commit to following [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), which dropped 3.9 support in April.

**Comment by peastman** [comment]
Ok, thanks.
